services:
  db:
    container_name: dbb
    image: postgres
    restart: unless-stopped
    environment:
        POSTGRES_USER: tenshiapp
        POSTGRES_PASSWORD: tenshiapp
        POSTGRES_DB: tenshiapp
    # volumes:
    #   - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenshiapp"]
      interval: 5s
    ports:
      - 5432:5432
