# version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: tenshiapp
        POSTGRES_PASSWORD: tenshiapp
        POSTGRES_DB: tenshiapp
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenshiapp"]
      interval: 8s
      timeout: 10s
      retries: 5
    ports:
      - 5432:5432
  app:
    container_name: app
    restart: always
    build:
      dockerfile: ./Containerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/tenshi
    links:
      - db