# version: '3.1'

services:

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: tenshiapp
        POSTGRES_PASSWORD: tenshiapp
        POSTGRES_DB: tenshiapp
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenshiapp"]
      interval: 5s
    ports:
      - 5432:5432
  migration:
    command: python3 manage.py migrate --no-input
    build:
      dockerfile: Containerfile
    depends_on:
      db:
        condition: service_healthy
  app:
    container_name: app
    restart: always
    build:
      dockerfile: ./Containerfile
    depends_on:
      - migration
      - db
    volumes:
      - .:/tenshi