services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
        POSTGRES_USER: tenshiapp
        POSTGRES_PASSWORD: tenshiapp
        POSTGRES_DB: tenshiapp
    volumes:
      - /var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tenshiapp"]
      interval: 5s
    networks:
      - tenshinet
    ports:
      - 5432:5432
  migration:
    command: python3 manage.py migrate --no-input
    build:
      dockerfile: Containerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_NAME: tenshiapp
      DATABASE_USERNAME: tenshiapp
      DATABASE_PASSWORD: tenshiapp
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
    networks:
      - tenshinet
  app:
    container_name: app
    environment:
      DATABASE_NAME: tenshiapp
      DATABASE_USERNAME: tenshiapp
      DATABASE_PASSWORD: tenshiapp
      DATABASE_PORT: 5432
      DATABASE_HOST: db
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    restart: always
    build:
      dockerfile: Containerfile
    ports: ["8080:8080"]
    depends_on:
      - migration
      - db
    volumes:
      - .:/app/tenshi
    networks:
      - tenshinet
networks:
  tenshinet: